In [10]:
#set up path and dependencies
import pandas as pd

schools_test_results_data = "Resources/schools_complete.csv"
students_test_results_data = "Resources/students_complete.csv"

#read data, create pandas data frames
school_test_results = pd.read_csv(schools_test_results_data)
student_test_results = pd.read_csv(students_test_results_data)

#merge both sets of data into one
total_test_results = pd.merge(school_test_results, student_test_results, how = "left", on = ["school_name", "school_name"])

In [29]:
#District Summary: total # of schools, students, budget, avg. math and reading scores
schools_total = total_test_results["school_name"].unique())
students_total = total_test_results["Student ID"].count()
budget_total = schools_test_results_data["budget"].sum()
math_score_avg = total_test_results["math_score"].mean()
reading_score_avg = total_test_results["reading_score"].mean()
students_passing_rate = (math_score_avg + reading_score_avg) / 2

#Percentages: passing math score, reading score, both math and reading 
students_passing_math = total_test_results[(total_test_results["math_score"] >= 70)].count()["student_name"]
passing_math_percentage = students_passing_math / float(students_total) * 100
students_passing_reading = total_test_results[(total_test_results["reading_score"] >= 70)].count()["student_name"]
passing_reading_percentage = students_passing_reading / float(students_total) * 100

#Data frame with results
district_total = pd.DataFrame({"Total Schools": [schools_total], 
                                 "Total Students": [students_total], 
                                 "Total Budget": [budget_total],
                                 "Average Math Score": [math_score_avg], 
                                 "Average Reading Score": [reading_score_avg],
                                 "% Passing Math": [passing_math_percentage],
                                 "% Passing Reading": [passing_reading_percentage],
                                 "% Overall Passing Rate": [students_passing_rate]})

district_total = district_total[["Total Schools", "Total Students", "Total Budget",
                                 "Average Math Score",
                                 "Average Reading Score",
                                 "% Passing Math",
                                 "% Passing Reading",
                                 "% Overall Passing rate"]]

#formatting 
district_total["Total Students"] = district_total["Total Students"].map("{:,}".format)
district_total["Total Budget"] = district_total["Total Budget"].map("${:,.2f}".format)

district_total

SyntaxError: invalid syntax (<ipython-input-29-d6256f0d1024>, line 2)

In [30]:
#School Summary: School name, type, # of students, general and per student budget
schools_type = school_test_results.set_index(["school_name"])["type"]
students_per_school = total_test_results["school_name"].value_counts()
school_budget = total_test_results.groupby(["school_name"]).mean()["budget"]
school_spending = school_budget / students_per_school

#School Summary: Avg, math score, reading score, % of both passing reading and math
math_students_ps = total_test_results.groupby(["school_name"]).mean()["math_score"]
reading_students_ps = total_test_results.groupby(["school_name"]).mean()["reading_score"]

#conditions to determine scores
math_schools_ps = total_test_results[(total_test_results["math_score"] >= 70)]
reading_schools_ps = total_test_results[(total_test_results["reading_score"] >= 70)] 

student_ps_math = math_schools_ps.groupby(["school_name"]).count()["student_name"] / students_per_school * 100
student_ps_reading = reading_schools_ps.groupby(["school_name"].count()["student_name"] / students_per_school * 100
students_passing_rate = (student_ps_math + student_ps_reading) / 2

#Data Frame with results / formatting
school_summary = pd.DataFrame({"School Type": schools_type,
                               "Total Students": students_per_school,
                               "Total School Budget": school_budget,
                               "Per Student Budget": school_spending,
                               "Average Math Score": math_students_ps,
                               "Average Reading Score": reading_students_ps,
                               "% Passing Math": math_schools_ps,
                               "%Passing Reading": reading_schools_ps,
                               "%Overall Passing Rate": passing_rate})

school_summary = school_summary[["School Type", "Total Students", "Total School Budget", "Per Student Budget",
                                 "Average Math Score", "Average Reading Score",
                                 "% Passing Math", "% Passing Reading",
                                 "% Overall Passing Rate"]]

school_summary["Total School Budget"] = school_summary["Total SChool Budget"].map("${:,.2f}".format)
school_summary["Per Student Budget"] = school_summary["Per Student Budget"].map("{:,.2f}".format)

school_summary

SyntaxError: invalid syntax (<ipython-input-30-4594ea2bf120>, line 17)

In [20]:
#Top Performing Schools

top_performing_schools = school_summary.sort_valued(["%Overall Passing Rate"], ascending = False)
top_performing_schools.head()

NameError: name 'school_summary' is not defined

In [21]:
#Bottom Perfoming Schools
bottom_performing_schools =school_summary.sort_values(["%Overall Passing Rate"], ascending = True)
bottom_performing_schools.head()

NameError: name 'school_summary' is not defined

In [23]:
#Math Scores by Grade
nineth_grade = total_test_results[(total_test_results["grade"] == "9th")]
tenth_grade = total_test_results[(total_test_results["grade"] == "10th")]
eleventh_grade = total_test_results[(total_test_results["grade"] == "11th")]
twelfth_grade = total_test_results[(total_test_results["grade"] == "12th")]

#.groupby per school
scores_nineth = nineth_grade.groupby(["school_name"]).mean()["math_score"]
scores_tenth = tenth_grade.groupby(["school_name"]).mean()["math_score"]
scores_eleventh = eleventh_grade.groupby(["school_name"]).mean()["math_score"]
scores_twelth = twelfth_grade.groupby(["school_name"]).mean()["math_score"]

#Data frame with results
total_scores_by_grade = pd.DataFrame({"9th": scores_nineth, "10th": scores_tenth,
                                     "11th": scores_eleventh, "12th": scores_twelth})
total_scores_by_grade = total_scores_by_grade[["9th", "10th", "11th", "12th"]]
total_scores_by_grade.index.name = None

total_scores_by_grade

                             9th       10th       11th       12th
Bailey High School     77.083676  76.996772  77.515588  76.492218
Cabrera High School    83.094697  83.154506  82.765560  83.277487
Figueroa High School   76.403037  76.539974  76.884344  77.151369
Ford High School       77.361345  77.672316  76.918058  76.179963
Griffin High School    82.044010  84.229064  83.842105  83.356164
Hernandez High School  77.438495  77.337408  77.136029  77.186567
Holden High School     83.787402  83.429825  85.000000  82.855422
Huang High School      77.027251  75.908735  76.446602  77.225641
Johnson High School    77.187857  76.691117  77.491653  76.863248
Pena High School       83.625455  83.372000  84.328125  84.121547
Rodriguez High School  76.859966  76.612500  76.395626  77.690748
Shelton High School    83.420755  82.917411  83.383495  83.778976
Thomas High School     83.590022  83.087886  83.498795  83.497041
Wilson High School     83.085578  83.724422  83.195326  83.035794
Wright High School     83.264706  84.010288  83.836782  83.644986

In [24]:
#Reading Score by Grade
nineth_grade = total_test_results[(total_test_results["grade"] == "9th")]
tenth_grade = total_test_results[(total_test_results["grade"] == "10th")]
eleventh_grade = total_test_results[(total_test_results["grade"] == "11th")]
twelfth_grade = total_test_results[(total_test_results["grade"] == "12th")]

#.groupby per school
scores_nineth = nineth_grade.groupby(["school_name"]).mean()["reading_score"]
scores_tenth = tenth_grade.groupby(["school_name"]).mean()["reading_score"]
scores_eleventh = eleventh_grade.groupby(["school_name"]).mean()["reading_score"]
scores_twelth = twelfth_grade.groupby(["school_name"]).mean()["reading_score"]

#Data Frame with Results
total_scores_by_grade = pd.DataFrame({"9th": scores_nineth, "10th": scores_tenth,
                                      "11th": scores_eleventh, "12th": scores_twelth})
total_scores_by_grade = total_scores_by_grade[["9th", "10th", "11th", "12th"]]
total_scores_by_grade.index.name = None

total_scores_by_grade

                             9th       10th       11th       12th
Bailey High School     81.303155  80.907183  80.945643  80.912451
Cabrera High School    83.676136  84.253219  83.788382  84.287958
Figueroa High School   81.198598  81.408912  80.640339  81.384863
Ford High School       80.632653  81.262712  80.403642  80.662338
Griffin High School    83.369193  83.706897  84.288089  84.013699
Hernandez High School  80.866860  80.660147  81.396140  80.857143
Holden High School     83.677165  83.324561  83.815534  84.698795
Huang High School      81.290284  81.512386  81.417476  80.305983
Johnson High School    81.260714  80.773431  80.616027  81.227564
Pena High School       83.807273  83.612000  84.335938  84.591160
Rodriguez High School  80.993127  80.629808  80.864811  80.376426
Shelton High School    84.122642  83.441964  84.373786  82.781671
Thomas High School     83.728850  84.254157  83.585542  83.831361
Wilson High School     83.939778  84.021452  83.764608  84.317673
Wright High School     83.833333  83.812757  84.156322  84.073171

In [26]:
#Scores based on School Spending

budget_spending_bins = [0, 575, 600, 650, 675]
bins_names = ["<$575", "$575-600", "$600-650", "$650-675"]
school_summary["Spending Ranges (Per Students)"] = pd.cut(school_spending, budget_spending_bins, labels = bins_names)

#organize spending according to bins

math_scores_spending = school_summary.groupby(["Spending Ranges (Per Student)"]).mean()["Average Math Score"]
reading_scores_spending = school_summary.groupby(["Spending Ranges (Per Student)"]).mean()["Average Reading Score"]
math_passing_spending = school_summary.groupby(["Spending Ranges (Per Student)"]).mean()["% Passing Math"]
reading_passing_spending = school.summary.groupby(["Spending Ranges (Per Student)"]).mean()["% Passing reading"]
students_passing_rate = (math_passing_spending + reading_passing_spending) / 2

#Data Frame with results
school_spending_summary = pd.DataFrame({"Average Math Score": math_scores_spending,
                               "Average Reading Score": reading_scores_spending,
                               "% Passing Math": math_passing_spending,
                               "% Passing Reading": reading_passing_spending,
                               "% Overall Passing Rate": students_passing_rate})
school_spending_summary = school_spending_summary[["Average Math Score",
                                 "Average Reading Score",
                                 "% Passing Math", "% Passing Reading",
                                 "% Overall Passing Rate"]]
school_spending_summary

NameError: name 'school_spending' is not defined

In [27]:
#Classify test scores by School Size

school_size_bins = [0, 1000, 2000, 5000]
size_groups = ["Small (<1000)", "Medium (1000 - 2000)", " Large (2000-5000)"]

#Distribute data into selected bins

school_summary["School Size"] = pd.cut(school_summary["Total Students"], school_size_bins, labels=size_groups)

#Determine scores according to the bins

school_size_math = school_summary.groupby(["School Size"]).mean()["Average Math Score"]
school_size_reading = school_summary.groupby(["School Size"]).mean()["Average Reading Score"]
passing_size_math = school_summary.groupby(["School Size"]).mean()["% Passing Math"]
passing_size_reading = school_summary.groupby(["School Size"]).mean()["% Passing Reading"]
student_passing_rate = (passing_size_math + passing_size_reading) / 2

#Data Frame with results

school_size_summary = pd.DataFrame({"Average Math Score": school_size_math,
                                    "Average Reading Score": school_size_reading,
                                    "% Passing Math": passing_size_math,
                                    "% Passing Reading": passing_size_reading,
                                    "% Overall Passing Rate": student_passing_rate})

school_size_summary = school_size_summary[["Average Math Score",
                                           "Average Reading Score",
                                           "% Passing Math", "% Passing Reading",
                                           "% Overall Passing Rate"]]
school_size_summary

NameError: name 'school_summary' is not defined

In [28]:
# Classify Scores based on the School Type

math_scores_type = school_summary.groupby(["School Type"]).mean()["Average Math Score"]
reading_scores_type = school_summary.groupby(["School Type"]).mean()["Average Reading Score"]
math_passing_type = school_summary.groupby(["School Type"]).mean()["% Passing Math"]
reading_passing_type = school_summary.groupby(["School Type"]).mean()["% Passing Reading"]
student_passing_rate = (math_passing_type + reading_passing_type) / 2

#Data Frame with results

school_type_summary = pd.DataFrame({"Average Math Score": math_scores_by_grade,
                                    "Average Reading Score": reading_scores_type,
                                    "% Passing Math": math_passing_type,
                                    "% Passing Reading": reading_passing_type,
                                    "% Overall Passing Rate": students_passing_rate})

school_type_summary = school_type_summary[["Average Math Score",
                                           "Average Reading Score",
                                           "% Passing Math", "% Passing Reading",
                                           "% Overall Passing Rate"]]
school_type_summary

NameError: name 'school_summary' is not defined